import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Layout from "../components/layout";

export default function Home() {
    return (
        <Layout>
            <Head>
                <title>Home Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <div>
                <h1>Home Page</h1>
            </div>
        </Layout>
    );
}
