import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Layout from "../components/layout";

export default function Home() {
    return (
        <Layout>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <div>
                <h1>Home Page</h1>
                <p>
                    This is some random information and text that im writing
                    from the top of my head because I need placeholder content
                    maybe i should use lorem ipsum since that would be faster
                </p>
            </div>
        </Layout>
    );
}
